### PR TITLE
Update pbr-gold-1.3-2015-11-29.csv

### PR DESCRIPTION
**Pull request by keenoraralio**

### CODE REVIEW

**Comment by keenoraralio** [comment]
Hope these movesets will change in just a few days, weeks or months since these current movesets for most Pokémon have been used for almost four months.

**Comment by chfoo** [comment]
Wait, what? What are these change exactly? I'm not involved in the "PBR staff" in anyway.

**Comment by keenoraralio** [comment]
Actually, this is just only my suggested moveset proposal for 2016 and these movesets are not yet final for approval.

**Comment by keenoraralio** [comment]
You may want to ask one of the PBR staff to edit some or most of the movesets for you which will finally be confirmed after a few months.

**Comment by keenoraralio** [comment]
Don't worry about that. One of the administrators will have to edit my moveset suggestion as well just in time for New Year or beyond that time.

**Comment by chfoo** [comment]
Ok, I see. Hopefully they will take your changes in consideration.

When there are published changes, I will update my visualizer data with another csv file so it can be selected. Thanks for the concern. I am closing the issue but feel free to reply if there is still a problem.

**Pull request closed without merging**
